on:
  workflow_dispatch:

jobs:
  prebuild-job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "running prebuild job 1"

  prebuild-job-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "running prebuild job 2"

  wait-on-prebuild-jobs:
    runs-on: ubuntu-latest
    needs:
      - prebuild-job-1
      - prebuild-job-2
    steps:
      - run: echo "All prebuild jobs compete"

  build-job-1:
    runs-on: ubuntu-latest
    needs:
      - wait-on-prebuild-jobs
