on:
  workflow_dispatch:
    inputs:
      run-prebuild:
        type: boolean
        default: true
      run-post-build:
        type: boolean
        default: true
      run-quality:
        type: boolean
        default: true
      run-artifact-push:
        type: boolean
        default: true
      dispatch-deployments:
        type: boolean
        default: true

jobs:
  prebuild-job-1:
    if: inputs.run-prebuild
    runs-on: ubuntu-latest
    steps:
      - run: echo "running prebuild job 1"

  prebuild-job-2:
    if: inputs.run-prebuild
    runs-on: ubuntu-latest
    steps:
      - run: echo "running prebuild job 2"

  prebuild-job-3:
    if: inputs.run-prebuild
    runs-on: ubuntu-latest
    steps:
      - run: echo "running prebuild job 3"

  prebuild-job-4:
    if: inputs.run-prebuild
    runs-on: ubuntu-latest
    steps:
      - run: echo "running prebuild job 4"

  wait-on-prebuild-jobs:
    runs-on: ubuntu-latest
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-prebuild
    needs:
      - prebuild-job-1
      - prebuild-job-2
      - prebuild-job-3
      - prebuild-job-4
    steps:
      - run: echo "All prebuild jobs compete"

  build-job-1:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    needs:
      - wait-on-prebuild-jobs
    steps:
      - run: echo "Building Image 1"

  build-job-2:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    needs:
      - wait-on-prebuild-jobs
    steps:
      - run: echo "Building Image 2"

  build-job-3:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    needs:
      - wait-on-prebuild-jobs
    steps:
      - run: echo "Building Image 3"

  post-build-job-1:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-post-build
    runs-on: ubuntu-latest
    needs:
      - build-job-1
    steps:
      - run: echo "Post Build Image 1"

  post-build-job-2:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-post-build
    runs-on: ubuntu-latest
    needs:
      - build-job-2
    steps:
      - run: echo "Post Build Image 2"

  post-build-job-3:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-post-build
    runs-on: ubuntu-latest
    needs:
      - build-job-3
    steps:
      - run: echo "Post Build Image 3"

  quality-job-1:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-quality
    runs-on: ubuntu-latest
    needs:
      - post-build-job-1
    steps:
      - run: echo "Quality Image 1"

  quality-job-2:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-quality
    runs-on: ubuntu-latest
    needs:
      - post-build-job-2
    steps:
      - run: echo "Quality Image 2"

  quality-job-3:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-quality
    runs-on: ubuntu-latest
    needs:
      - post-build-job-3
    steps:
      - run: echo "Quality Image 3"

  post-quality-job-1:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-quality
    runs-on: ubuntu-latest
    needs:
      - quality-job-1
    steps:
      - run: echo "Post Quality Image 1"

  post-quality-job-2:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-quality
    runs-on: ubuntu-latest
    needs:
      - quality-job-2
    steps:
      - run: echo "Post Quality Image 2"

  post-quality-job-3:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-quality
    runs-on: ubuntu-latest
    needs:
      - quality-job-3
    steps:
      - run: echo "Post Quality Image 3"

  artifact-push-job-1:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-artifact-push
    runs-on: ubuntu-latest
    needs:
      - post-quality-job-1
    steps:
      - run: echo "Push Image 1"

  artifact-push-job-2:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-artifact-push
    runs-on: ubuntu-latest
    needs:
      - post-quality-job-2
    steps:
      - run: echo "Push Image 2"

  artifact-push-job-3:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-artifact-push
    runs-on: ubuntu-latest
    needs:
      - post-quality-job-3
    steps:
      - run: echo "Push Image 3"

  post-artifact-push-job-1:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-artifact-push
    runs-on: ubuntu-latest
    needs:
      - artifact-push-job-1
    steps:
      - run: echo "Post Push Image 1"

  post-artifact-push-job-2:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-artifact-push
    runs-on: ubuntu-latest
    needs:
      - artifact-push-job-2
    steps:
      - run: echo "Post Push Image 2"

  post-artifact-push-job-3:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.run-artifact-push
    runs-on: ubuntu-latest
    needs:
      - artifact-push-job-3
    steps:
      - run: echo "Post Push Image 3"

  # dispatch deployments
  wait-on-images-1:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.dispatch-deployments
    runs-on: ubuntu-latest
    needs:
      - post-artifact-push-job-1
      - post-artifact-push-job-3
    steps:
      - run: echo "Wait on Image 1"

  wait-on-images-2:
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && inputs.dispatch-deployments
    runs-on: ubuntu-latest
    needs:
      - post-artifact-push-job-2
    steps:
      - run: echo "Wait on Image 1"
