on:
  workflow_dispatch:
    inputs:
      run-prebuild:
        type: boolean
        default: true

jobs:
  prebuild-job-1:
    if: inputs.run-prebuild
    runs-on: ubuntu-latest
    steps:
      - run: echo "running prebuild job 1"

  prebuild-job-2:
    if: inputs.run-prebuild
    runs-on: ubuntu-latest
    steps:
      - run: echo "running prebuild job 2"

  wait-on-prebuild-jobs:
    runs-on: ubuntu-latest
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    needs:
      - prebuild-job-1
      - prebuild-job-2
    steps:
      - run: echo "All prebuild jobs compete"

  build-job-1:
    runs-on: ubuntu-latest
    needs:
      - wait-on-prebuild-jobs
    steps:
      - run: echo "Building Image 1"

  build-job-2:
    runs-on: ubuntu-latest
    needs:
      - wait-on-prebuild-jobs
    steps:
      - run: echo "Building Image 2"

  build-job-3:
    runs-on: ubuntu-latest
    needs:
      - wait-on-prebuild-jobs
    steps:
      - run: echo "Building Image 2"
