on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Output Caller Workflow Details
        run: |
          echo "Workflow Name: ${{ github.event.workflow_run.name }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Duration: $(( ($(date -d "${{ github.event.workflow_run.updated_at }}" +%s) - $(date -d "${{ github.event.workflow_run.run_started_at }}" +%s)) / 60 )) minutes"
          echo "Branch: https://github.com/${{ github.repository }}/tree/${{ github.event.workflow_run.head_branch }}"
          echo "Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
