name: Deployment Event Listener

on:
  deployment:
  deployment_status:

jobs:
  handle-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Handle Deployment Created
        if: ${{ github.event_name == 'deployment' && github.event.action == 'created' }}
        run: |
          echo "Deployment created for environment: ${{ github.event.deployment.environment }}"

      - name: Handle Deployment Pending
        if: ${{ github.event_name == 'deployment_status' && github.event.deployment_status.state == 'pending' }}
        run: |
          echo "Deployment is pending for environment: ${{ github.event.deployment.environment }}"

      - name: Handle Deployment Success
        if: ${{ github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' }}
        run: |
          echo "Deployment succeeded for environment: ${{ github.event.deployment.environment }}"

      - name: Handle Deployment Failure
        if: ${{ github.event_name == 'deployment_status' && github.event.deployment_status.state == 'failure' }}
        run: |
          echo "Deployment failed for environment: ${{ github.event.deployment.environment }}"

      - name: Handle Deployment Error
        if: ${{ github.event_name == 'deployment_status' && github.event.deployment_status.state == 'error' }}
        run: |
          echo "Deployment encountered an error for environment: ${{ github.event.deployment.environment }}"
