name: Deployment Event Listener

on:
  deployment:
  deployment_status:

jobs:
  prepare-message:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Workflow Details
        id: extract-details
        run: |
          echo "🚀 Deployment Details:"
          echo "Environment: ${{ github.event.deployment.environment }}"
          echo "Triggered By: ${{ github.event.deployment.creator.login }}"

      - name: Extract Status Details
        if: ${{ github.event_name == 'deployment_status' }}
        run: |
          echo "Status: ${{ github.event.deployment_status.state }}"
          echo "Target URL: ${{ github.event.deployment_status.target_url }}"
          echo "Log URL: ${{ github.event.deployment_status.log_url }}"
