name: Deployment Event Listener

on:
  deployment_status:

jobs:
  prepare-message:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Workflow Details
        id: extract-details
        run: |
          echo "🚀 Deployment Details:"
          echo "ENVIRONMENT=${{ github.event.deployment.environment }}" >> $GITHUB_ENV
          echo "ACTOR=${{ github.event.deployment.creator.login }}" >> $GITHUB_ENV

      - name: Extract Status Details
        if: ${{ github.event_name == 'deployment_status' }}
        run: |
          echo "STATUS=${{ github.event.deployment_status.state }}" >> $GITHUB_ENV
          echo "URL=${{ github.event.deployment_status.target_url }}" >> $GITHUB_ENV
