on:
  workflow_dispatch:
    inputs:
      components:
        type: string
        required: true
        default: test1,test2
        description: Component list
      image_tag:
        type: string
        required: true
        description: Image Tag for components
      ref:
        type: string
        required: true
        default: Specific git ref to tag

  push:
    branches:
      - main
      - release/**
      - hotfix/**

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          ref: ${{ inputs.ref }}

      - name: Get branch name
        id: branch
        run: |
          if ! [[ "${{ inputs.components }}" =~ ^[^,]+(,[^,]+)*$ ]]; then
            echo "::error::components must be a comma-separated list (e.g., comp1,comp2)"
            exit 1
          fi

          branch=release/${{inputs.image_tag}}/${{inputs.components}}

          echo $branch
          echo branch=$branch >> $GITHUB_OUTPUT

      - name: Check branch
        id: branch_exists
        run: |
          BRANCH="${{ steps.branch.outputs.branch }}"

          if git ls-remote --heads origin "$BRANCH" | grep -q "$BRANCH"; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
            echo "Branch $BRANCH already exists"
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
            echo "Branch $BRANCH does not exist"
          fi

      - name: Create branch
        if: steps.branch_exists.outputs.branch_exists == 'false'
        run: |
          git checkout -b ${{ steps.branch.outputs.branch }}
          git push -u origin ${{ steps.branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check tag exists
        id: tag_exists
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          TAG_EXISTS=$(git tag --points-at $COMMIT_SHA)

          if [ -n "$TAG_EXISTS" ]; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
            echo "Existing tag: $TAG_EXISTS"
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
            echo "No tag found for this SHA"
          fi

      - name: Bump patch version and create tag
        id: patch_bump
        run: |
          # Get latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")

          # Extract version components
          IFS='.' read -ra VERSION <<< "${LATEST_TAG#v}"
          MAJOR=${VERSION[0]}
          MINOR=${VERSION[1]}
          PATCH=${VERSION[2]}

          # Increment patch version
          PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"

          # Create new tag
          git tag $NEW_TAG
          git push origin $NEW_TAG

          # Output new tag
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check release exists
        id: release_exists
        run: |
          TAG="${{ steps.patch_bump.outputs.new_tag }}"

          if gh release view "$TAG" --json name > /dev/null 2>&1; then
            echo "release_exists=true" >> $GITHUB_OUTPUT
            echo "Release $TAG already exists"
          else
            echo "release_exists=false" >> $GITHUB_OUTPUT
            echo "Release $TAG does not exist"
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Generate release notes
        id: release_notes
        if: steps.release_exists.outputs.release_exists == 'false'
        run: |
          COMPONENTS="${{ inputs.components }}"
          TAG="${{ steps.patch_bump.outputs.new_tag }}"

          # Get the previous tag to generate diff
          PREV_TAG=$(git tag --sort=-version:refname | grep -v "$TAG" | head -n 1 || echo "")

          # Generate release notes
          echo "## Components" > release_notes.md

          IFS=',' read -ra COMP_ARRAY <<< "$COMPONENTS"
          for comp in "${COMP_ARRAY[@]}"; do
            echo "- $comp" >> release_notes.md
          done

          echo "" >> release_notes.md
          echo "## Changes" >> release_notes.md

          if [ -n "$PREV_TAG" ]; then
            git log $PREV_TAG..HEAD --pretty=format:"* %s (%h)" >> release_notes.md
          else
            git log --pretty=format:"* %s (%h)" >> release_notes.md
          fi

          echo "notes_file=release_notes.md" >> $GITHUB_OUTPUT

      - name: Create release
        if: steps.release_exists.outputs.release_exists == 'false'
        run: |
          gh release create ${{ steps.patch_bump.outputs.new_tag }} \
            --title "Release ${{ steps.patch_bump.outputs.new_tag }}" \
            --notes-file ${{ steps.release_notes.outputs.notes_file }} \
            --target ${{ steps.branch.outputs.branch }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Update release
        if: steps.release_exists.outputs.release_exists == 'true'
        run: |
          # Generate updated notes for existing release
          COMPONENTS="${{ inputs.components }}"
          TAG="${{ steps.patch_bump.outputs.new_tag }}"

          echo "## Components" > updated_notes.md

          IFS=',' read -ra COMP_ARRAY <<< "$COMPONENTS"
          for comp in "${COMP_ARRAY[@]}"; do
            echo "- $comp" >> updated_notes.md
          done

          # Update the existing release
          gh release edit ${{ steps.patch_bump.outputs.new_tag }} \
            --notes-file updated_notes.md
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload component list to release
        run: |
          COMPONENTS="${{ inputs.components }}"
          touch components.txt
          IFS=',' read -ra COMP_ARRAY <<< "$COMPONENTS"
          for comp in "${COMP_ARRAY[@]}"; do
            echo "- $comp" >> components.txt
          done

          gh release upload ${{ steps.patch_bump.outputs.new_tag }} components.txt --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
