on:
  workflow_dispatch:
    inputs:
      components:
        type: string
        required: true
        default: test1,test2
      tag:
        type: string
        required: true
        default: v1.2.3
      ref:
        type: string
        required: true
        default: main
  push:
    branches:
      - main
      - release/**
      - hotfix/**

jobs:
  manage-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Get branch name
        id: branch
        run: |

          if ! [[ "${{ inputs.components }}" =~ ^[^,]+(,[^,]+)*$ ]]; then
            echo "::error::components must be a comma-separated list (e.g., comp1,comp2)"
            exit 1
          fi

          branch=release/${{inputs.tag}}/${{inputs.components}}

          echo $branch
          echo branch=$branch >> $GITHUB_OUTPUT

      - name: Check branch
        id: branch_exists
        run: |
          BRANCH="${{ steps.branch.outputs.branch }}"

          if git ls-remote --heads origin "$BRANCH" | grep -q "$BRANCH"; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
            echo "Branch $BRANCH already exists"
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
            echo "Branch $BRANCH does not exist"
          fi

      - name: Create branch
        if: steps.branch_exists.outputs.branch_exists == 'false'
        run: |
          git checkout -b ${{ steps.branch.outputs.branch }}
          git push -u origin ${{ steps.branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
