on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Image Tag for components
      ref:
        type: string
        required: true
        description: Specific git ref to tag

  push:
    branches:
      - release/**

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Get branch name
        id: branch
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            branch=release/${{ inputs.tag }}
          else
            branch="${GITHUB_REF#refs/heads/}"
          fi
          echo "branch=$branch" >> $GITHUB_OUTPUT

      - name: Check if branch exists
        id: branch_exists
        if: github.event_name == 'workflow_dispatch'
        run: |
          BRANCH="${{ steps.branch.outputs.branch }}"
          if git ls-remote --heads origin "$BRANCH" | grep -q "$BRANCH"; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create branch
        if: github.event_name == 'workflow_dispatch' && steps.branch_exists.outputs.branch_exists == 'false'
        run: |
          git checkout -b ${{ steps.branch.outputs.branch }}
          git push -u origin ${{ steps.branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.branch.outputs.branch }}

      - name: Set components and tag for push event
        id: vars
        run: |
          BRANCH="${{ steps.branch.outputs.branch }}"
          SHORT_SHA="${GITHUB_SHA:0:7}"
          IMAGE_TAG=$(echo "$BRANCH" | cut -d'/' -f2)
          GIT_TAG="${IMAGE_TAG}-${SHORT_SHA}"

          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

          # Get the latest SemVer tag (fallback to v0.0.0 if none exists)
          LATEST_TAG=$(git tag --list 'v*' --sort=-v:refname | head -n 1)
          LATEST_TAG=${LATEST_TAG:-"v0.0.0"}

          # Remove pre-release (-...) and metadata (+...) parts
          CLEAN_TAG=$(echo "$LATEST_TAG" | sed -E 's/[-+].*//')

          # Extract major, minor, and patch versions
          VERSION=$(echo "$CLEAN_TAG" | sed -E 's/^v//')
          MAJOR=$(echo "$VERSION" | cut -d'.' -f1)
          MINOR=$(echo "$VERSION" | cut -d'.' -f2)

          # Extract PATCH correctly, even if LATEST_TAG had '-' or '+'
          PATCH=$(echo "$VERSION" | cut -d'.' -f3)
          PATCH=${PATCH:-0}  # Default to 0 if empty

          # Increment PATCH version
          NEW_PATCH=$((PATCH + 1))
          NEW_TAG="v${MAJOR}.${MINOR}.${NEW_PATCH}"

          NEW_TAG="${NEW_TAG}+${IMAGE_TAG}"

          echo "last_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "git_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: tag_exists
        run: |
          TAG="${{ steps.vars.outputs.git_tag }}"
          if git ls-remote --tags origin refs/tags/$TAG | grep -q $TAG; then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create tag
        if: steps.tag_exists.outputs.tag_exists == 'false'
        run: |
          git tag ${{ steps.vars.outputs.git_tag }}
          git push origin ${{ steps.vars.outputs.git_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if release exists
        id: release_exists
        run: |
          TAG="${{ steps.vars.outputs.git_tag }}"
          if gh release view "$TAG" --json name > /dev/null 2>&1; then
            echo "release_exists=true" >> $GITHUB_OUTPUT
          else
            echo "release_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        if: steps.release_exists.outputs.release_exists == 'false'
        run: |
          gh release create ${{ steps.vars.outputs.git_tag }} \
            --title "Release ${{ steps.vars.outputs.git_tag }}" \
            --target ${{ github.sha }} \
            --latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
