on:
  workflow_dispatch:
    inputs:
      components:
        type: string
        required: true
      tag:
        type: string
        required: true
      sha:
        type: string
        required: true
  push:
    branches:
      - release/**
      - hotfix/**

jobs:
  manage-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Get branch name
        id: branch
        run: |

          if ! [[ "${{ inputs.components }}" =~ ^[^,]+(,[^,]+)*$ ]]; then
            echo "::error::components must be a comma-separated list (e.g., comp1,comp2)"
            exit 1
          fi

          branch=release/${{inputs.tag}}/${{inputs.components}}

          echo $branch
          echo branch=$branch >> $GITHUB_OUTPUT

      - name: Check branch
        id: branch_exists
        run: |
          BRANCH="${{ steps.branch.outputs.branch }}"

          if git ls-remote --heads origin "$BRANCH" | grep -q "$BRANCH"; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
            echo "Branch $BRANCH already exists"
          else
            echo "branch_exists=false" >> $GITHUB_OUTPUT
            echo "Branch $BRANCH does not exist"
          fi
