name: Deploy test

on:
  release:
  push:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test-dev:
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson('["pull_request", "push", "release", "schedule"]'), github.event_name) }}
    environment: dev
    steps:
      - run: |
          echo "Generating a random number"
          echo "Group=${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}"
          echo "Cancel=${{ github.ref != 'refs/heads/main' }}"
