name: Deploy test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate random failure
        run: |
          echo "Generating a random number..."
          RANDOM_NUMBER=$(( RANDOM % 2 ))
          echo "Random number: $RANDOM_NUMBER"
          if [ $RANDOM_NUMBER -eq 0 ]; then
            echo "Simulating failure..."
            exit 1
          else
            echo "Simulating success..."
          fi
