on:
  release:

jobs:
  on-prerelease:
    if: github.event.release.prerelease
    runs-on: ubuntu-default
    steps:
      - name: Debug GitHub Event
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Is Prerelease: ${{ github.event.release.prerelease }}"
      - run: echo "hello"
        if: github.event.release.prerelease
