name: Deploy test

on:
  release:

jobs:
  test-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == false && github.event_name == 'release' }}
    environment: dev
    steps:
      - run: |
          echo "Generating a random number"
          echo "Group=${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}"
          echo "Cancel=${{ github.ref != 'refs/heads/main' }}"
