on:
  pull_request:
    types:
      - closed
  release:
    types:
      - published

jobs:
  needs:
    if: ${{github.event.release.prerelease || github.event.pull_request.merged == true}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
