name: Deploy test

on:
  push:
  workflow_dispatch:

jobs:
  test-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: |
          echo "Generating a random number..."

  test-prod:
    runs-on: ubuntu-latest
    needs: test-dev
    environment: prod
    steps:
      - name: Simulate random failure
        run: |
          echo "Generating a random number..."
          RANDOM_NUMBER=$(( RANDOM % 2 ))
          echo "Random number: $RANDOM_NUMBER"
          if [ $RANDOM_NUMBER -eq 0 ]; then
            echo "Simulating failure..."
            exit 1
          else
            echo "Simulating success..."
          fi
