name: Deploy test

on:
  release:
  push:
  # schedule:
  #   - cron: "*/1 * * * *"

jobs:
  test-dev:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    environment: dev
    steps:
      - name: Print Debug Information
        run: |
          echo "Generating a random number"
          echo "Group=${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}"
          echo "Cancel=${{ github.ref != 'refs/heads/main' }}"

  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Print Debug Information
        run: |
          echo "Generating a random number"
          echo "Group=${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}"
          echo "Cancel=${{ github.ref != 'refs/heads/main' }}"
