name: Test
on:
  push:

jobs:
  needs:
    runs-on: ubuntu-latest
    steps:
      - name: "Randomly Fail"
        run: |
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "Failure";
            exit 1;
          fi
          echo "Success";
