on:
  release:
    types:
      - published

jobs:
  always:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Event
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Is Prerelease: ${{ github.event.release.prerelease }}"

  on-prerelease:
    if: github.event.release.prerelease
    needs: always
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
        if: github.event.release.prerelease

  on-prerelease2:
    needs: always
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
        if: github.event.release.prerelease
